# Generated by Django 4.2.14 on 2026-07-01 06:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make_model', models.CharField(help_text='e.g. Cessna 152', max_length=100)),
                ('icao_designator', models.CharField(blank=True, max_length=10, null=True)),
                ('engine_make_model', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(default='AVGAS 100LL', max_length=20)),
                ('oil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('max_crosswind_demo_kt', models.DecimalField(decimal_places=1, default=15.0, max_digits=4)),
                ('max_crosswind_student_kt', models.DecimalField(decimal_places=1, default=12.0, max_digits=4)),
                ('da_solo_warning_ft', models.IntegerField(default=5500)),
                ('interval_50hr', models.DecimalField(decimal_places=1, default=50.0, max_digits=6)),
                ('interval_100hr', models.DecimalField(decimal_places=1, default=100.0, max_digits=6)),
                ('interval_200hr', models.DecimalField(decimal_places=1, default=200.0, max_digits=6)),
                ('interval_600hr', models.DecimalField(decimal_places=1, default=600.0, max_digits=6)),
                ('interval_annual_months', models.IntegerField(default=12)),
                ('interval_biennial_months', models.IntegerField(default=24)),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
                'db_table': 'aircraft_types',
                'ordering': ['make_model'],
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icao_code', models.CharField(max_length=4, unique=True)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True)),
                ('base_type', models.CharField(choices=[('hub', 'Hub (Central Maintenance)'), ('satellite', 'Satellite Base')], default='satellite', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation_ft', models.IntegerField(default=0)),
                ('ferry_buffer_hours', models.DecimalField(decimal_places=2, default=2.5, help_text='Hours reserved for ferry flight back to hub. 0 for the hub itself.', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
                'db_table': 'bases',
                'ordering': ['-base_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tail_number', models.CharField(help_text='e.g. VT-ABC', max_length=10, unique=True)),
                ('status', models.CharField(choices=[('airworthy', 'Airworthy'), ('aog', 'AOG (Aircraft on Ground)'), ('scheduled_maintenance', 'Scheduled Maintenance'), ('ferry_required', 'Ferry Required'), ('deregistered', 'Deregistered')], db_index=True, default='airworthy', max_length=30)),
                ('aog_reason', models.TextField(blank=True, null=True)),
                ('aog_since', models.DateTimeField(blank=True, null=True)),
                ('hobbs_total', models.DecimalField(decimal_places=1, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tacho_total', models.DecimalField(decimal_places=1, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_50hr_at', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('next_100hr_at', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('next_200hr_at', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('next_600hr_at', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('next_annual_due', models.DateField(blank=True, null=True)),
                ('next_biennial_due', models.DateField(blank=True, null=True)),
                ('cert_of_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('cert_of_airworthiness', models.CharField(blank=True, max_length=50, null=True)),
                ('coa_expiry', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='infrastructure.aircrafttype')),
                ('current_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_aircraft', to='infrastructure.base')),
                ('home_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_aircraft', to='infrastructure.base')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'db_table': 'aircraft',
                'ordering': ['tail_number'],
            },
        ),
    ]
