# Generated by Django 4.2.14 on 2026-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='is_multi_engine',
            field=models.BooleanField(default=False, help_text='True if aircraft has multiple engines (e.g. DA42, P68, PA34)'),
        ),
    ]
