# Generated by Django 4.2.14 on 2026-08-01 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_aircrafttype_is_multi_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runway_identifier', models.CharField(help_text='e.g. 09/27 or 09L/27R', max_length=10)),
                ('heading_deg', models.SmallIntegerField(help_text='Primary heading 0-359')),
                ('reciprocal_heading_deg', models.SmallIntegerField(help_text='Reciprocal heading 0-359')),
                ('length_ft', models.IntegerField(blank=True, null=True)),
                ('width_ft', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='infrastructure.base')),
            ],
            options={
                'db_table': 'runways',
                'ordering': ['base', 'runway_identifier'],
            },
        ),
        migrations.AddField(
            model_name='base',
            name='active_runway',
            field=models.ForeignKey(blank=True, help_text='Currently active runway for dispatch crosswind calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='infrastructure.runway'),
        ),
    ]
