# Generated by Django 4.2.14 on 2026-08-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_runway_base_active_runway'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='cruise_speed_knots',
            field=models.IntegerField(blank=True, help_text='Typical cruise speed (knots) for range calculation', null=True),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='max_range_nm',
            field=models.IntegerField(blank=True, help_text='Max range in nautical miles (no reserves) — for informational CC validation only', null=True),
        ),
    ]
