"""
Management Command: python manage.py seed_sample_aircraft

INSTRUCTIONS FOR USER:
1. Open and edit the AIRCRAFT_TYPES and AIRCRAFT_FLEET data structures below with your actual fleet details.
2. When ready, execute:
      python manage.py seed_sample_aircraft
   or (inside Docker container):
      docker compose exec api python manage.py seed_sample_aircraft
"""

import datetime
from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.infrastructure.models import Base, AircraftType, Aircraft


# ==============================================================================
# EDITABLE SEED DATA CONFIGURATION
# ==============================================================================

# 2. Sample Aircraft Fleet Definition
# Note: Base codes refer to Base.icao_code in the DB (e.g. 'VAAM' for Amravati Hub)
AIRCRAFT_FLEET_DATA = [
    {
        "tail_number": "VT-FTA",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284100",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTB",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284101",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTC",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284102",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTD",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284103",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTE",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284104",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTF",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284105",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTG",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284106",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTH",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284107",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTI",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284108",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTJ",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284109",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTK",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284110",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTM",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284111",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTN",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284112",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTP",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284113",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTQ",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284114",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTR",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284115",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTS",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284116",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTT",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284117",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTU",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284118",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTW",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284119",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTX",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284120",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTY",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284121",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FTZ",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284122",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAG",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284123",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAH",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284124",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAI",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284125",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAJ",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284126",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAK",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284127",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAQ",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284128",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAT",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284129",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAU",
        "aircraft_type_make_model": "Piper PA 28",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284130",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Single Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAX",
        "aircraft_type_make_model": "Diamond DA42NG",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284131",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Multi Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAY",
        "aircraft_type_make_model": "Diamond DA42NG",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284132",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Multi Engine trainer at AIFA.",
    },
    {
        "tail_number": "VT-FAZ",
        "aircraft_type_make_model": "Diamond DA42NG",
        "home_base_icao": "VAAM",
        "current_base_icao": "VAAM",
        "status": Aircraft.Status.AIRWORTHY,
        "aog_reason": None,
        "hobbs_total": Decimal("0.0"),
        "tacho_total": Decimal("0.0"),
        "next_50hr_at": Decimal("50.0"),
        "next_100hr_at": Decimal("100.0"),
        "next_200hr_at": Decimal("200.0"),
        "next_600hr_at": Decimal("600.0"),
        "next_annual_due": datetime.date(2026, 12, 15),
        "next_biennial_due": datetime.date(2027, 12, 15),
        "cert_of_registration": "C-Reg/2020/001",
        "cert_of_airworthiness": "C-Air/2024/789",
        "coa_expiry": datetime.date(2027, 5, 30),
        "serial_number": "15284133",
        "year_of_manufacture": 2025,
        "is_active": True,
        "notes": "Multi Engine trainer at AIFA.",
    },
]


# ==============================================================================
# MANAGEMENT COMMAND LOGIC
# ==============================================================================

class Command(BaseCommand):
    help = "Seeds aircraft types and sample aircraft fleet into the database."

    def handle(self, *args, **options):
        self.stdout.write(self.style.MIGRATE_HEADING("--- Starting Aircraft Seed Command ---"))

        # 2. Seed Aircraft Fleet
        for aircraft_data in AIRCRAFT_FLEET_DATA:
            tail = aircraft_data.pop("tail_number")
            type_name = aircraft_data.pop("aircraft_type_make_model")
            home_base_icao = aircraft_data.pop("home_base_icao")
            current_base_icao = aircraft_data.pop("current_base_icao")

            # Resolve Foreign Keys
            atype = AircraftType.objects.filter(make_model=type_name).first()
            if not atype:
                self.stdout.write(self.style.ERROR(f"  ✗ Skipping {tail}: AircraftType '{type_name}' not found!"))
                continue

            home_base = Base.objects.filter(icao_code=home_base_icao).first()
            if not home_base:
                self.stdout.write(self.style.ERROR(f"  ✗ Skipping {tail}: Home Base '{home_base_icao}' not found!"))
                continue

            current_base = Base.objects.filter(icao_code=current_base_icao).first() or home_base

            # Create or update Aircraft
            obj, created = Aircraft.objects.update_or_create(
                tail_number=tail,
                defaults={
                    "aircraft_type": atype,
                    "home_base": home_base,
                    "current_base": current_base,
                    **aircraft_data
                }
            )
            action = "Created" if created else "Updated"
            self.stdout.write(self.style.SUCCESS(f"  ✓ {action} Aircraft: {tail} ({atype.make_model})"))

        self.stdout.write(self.style.MIGRATE_HEADING("--- Aircraft Seeding Complete ---"))
