# Generated by Django 4.2.14 on 2026-07-01 06:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licence_type', models.CharField(choices=[('PPL', 'Private Pilot Licence'), ('CPL', 'Commercial Pilot Licence')], default='CPL', max_length=10)),
                ('stage_number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence_order', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'syllabus_stages',
                'ordering': ['licence_type', 'sequence_order'],
                'unique_together': {('licence_type', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusLesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('sequence_order', models.SmallIntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='syllabus.syllabusstage')),
            ],
            options={
                'db_table': 'syllabus_lessons',
                'ordering': ['sequence_order'],
                'unique_together': {('stage', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_code', models.CharField(help_text='e.g. EX-4A', max_length=20)),
                ('title', models.CharField(help_text='e.g. Steep Turns', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('flight_type_required', models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo'), ('cross_country_dual', 'Cross-Country Dual'), ('cross_country_solo', 'Cross-Country Solo'), ('night_dual', 'Night Dual'), ('night_solo', 'Night Solo'), ('instrument', 'Instrument')], default='dual', max_length=30)),
                ('prerequisite_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('pass_grade', models.SmallIntegerField(default=3, help_text='Minimum grade (1–5) to clear this exercise')),
                ('sequence_order', models.SmallIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='syllabus.syllabuslesson')),
            ],
            options={
                'db_table': 'syllabus_exercises',
                'ordering': ['sequence_order'],
                'unique_together': {('lesson', 'exercise_code')},
            },
        ),
    ]
