# Generated by Django 4.2.14 on 2026-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusexercise',
            name='is_buffer',
            field=models.BooleanField(default=False, help_text='If true, instructors can schedule without CFI override.'),
        ),
        migrations.AlterField(
            model_name='syllabusexercise',
            name='flight_type_required',
            field=models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo'), ('cross_country_dual', 'Cross-Country Dual'), ('cross_country_solo', 'Cross-Country Solo'), ('night_dual', 'Night Dual'), ('night_solo', 'Night Solo'), ('instrument', 'Instrument'), ('progress_check', 'Progress Check'), ('proficiency_check', 'Proficiency Check'), ('buffer', 'Buffer')], default='dual', max_length=30),
        ),
    ]
