# Generated by Django 4.2.14 on 2026-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_syllabusexercise_is_buffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusexercise',
            name='dual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='fstd_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='instrument_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='is_knowledge_test',
            field=models.BooleanField(default=False, help_text='True for K1..K12 ground/oral tests'),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='log_as_p1_us',
            field=models.BooleanField(default=False, help_text='If true, passed test is logged as P1 U/S (SOLO) in student logbook'),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='solo_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='syllabusexercise',
            name='flight_type_required',
            field=models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo'), ('cross_country_dual', 'Cross-Country Dual'), ('cross_country_solo', 'Cross-Country Solo'), ('night_dual', 'Night Dual'), ('night_solo', 'Night Solo'), ('instrument', 'Instrument'), ('dual_instrument', 'Dual Instrument'), ('dual_multi_engine', 'Dual Multi-Engine'), ('progress_check', 'Progress Check'), ('proficiency_check', 'Proficiency Check'), ('knowledge_test', 'Ground Knowledge Test'), ('ground_training', 'Ground Training'), ('licensing_process', 'Licensing Process'), ('fstd_instrument', 'FSTD Simulator Instrument'), ('fstd_progress_check', 'FSTD Simulator Progress Check'), ('dgca_flight_test', 'DGCA Flight Test (P1 U/S Logged)'), ('buffer', 'Buffer')], default='dual', max_length=40),
        ),
    ]
