# Generated by Django 4.2.14 on 2026-08-06 10:37

from django.db import migrations, models
import django.db.models.deletion


def seed_initial_licence_types(apps, schema_editor):
    LicenceType = apps.get_model('syllabus', 'LicenceType')
    LicenceType.objects.get_or_create(code='CPL', defaults={'name': 'Commercial Pilot Licence', 'is_active': True})
    LicenceType.objects.get_or_create(code='PPL', defaults={'name': 'Private Pilot Licence', 'is_active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_alter_syllabusexercise_flight_type_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. CPL, PPL, ATPL', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name, e.g. Commercial Pilot Licence', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'licence_types',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_initial_licence_types, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='syllabusstage',
            name='licence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='syllabus.licencetype'),
        ),
    ]
