# Generated by Django 4.2.14 on 2026-08-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_licencetype_alter_syllabusstage_licence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabusexercise',
            name='flight_type_required',
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_flight_type',
            field=models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo')], default='dual', max_length=10),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_is_cross_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_is_instructional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_is_instrument_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_is_instrument_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_is_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_is_simulator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='default_is_skill_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabusexercise',
            name='is_ground_event',
            field=models.BooleanField(default=False, help_text='Knowledge tests & ground events - excluded from flight hours'),
        ),
    ]
