# Generated by Django 4.2.14 on 2026-08-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_remove_syllabusexercise_flight_type_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabusexercise',
            name='default_flight_type',
            field=models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo'), ('either', 'Either')], default='dual', max_length=10),
        ),
    ]
