# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('max_points', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name, e.g. 'Building2'", max_length=40)),
            ],
            options={
                'verbose_name': 'Audit Category',
                'verbose_name_plural': 'Audit Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('max_points', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('auto_scored', models.BooleanField(default=False, help_text='Computed live from DB; no manual entry needed')),
                ('scoring_logic_key', models.CharField(blank=True, help_text='Maps to AuditScoringEngine.score_<key>() method', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditParameterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('remarks', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, help_text='Upload to MinIO via presigned URL', null=True, upload_to='audit/evidence/')),
                ('auto_computed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField()),
                ('status', models.CharField(choices=[('live', 'Live – auto-computed'), ('draft', 'Draft'), ('completed', 'Completed'), ('submitted', 'Submitted to DGCA')], default='draft', max_length=20)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('auditor_name', models.CharField(blank=True, max_length=200)),
                ('auditor_designation', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=15)),
                ('category', models.CharField(choices=[('medical', 'Medical Currency'), ('aircraft', 'Aircraft Airworthiness'), ('fdtl', 'FDTL Limits'), ('spl', 'SPL / Exams'), ('training', 'Training Progress'), ('documentation', 'Documentation'), ('safety', 'Safety'), ('maintenance', 'Maintenance')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('likelihood', models.SmallIntegerField(help_text='1 (Rare) to 5 (Almost Certain)')),
                ('severity', models.SmallIntegerField(help_text='1 (Negligible) to 5 (Catastrophic)')),
                ('controls', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Risk Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hazard_entries',
                'ordering': ['-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('occurrence_type', models.CharField(choices=[('incident', 'Incident'), ('accident', 'Accident'), ('near_miss', 'Near Miss'), ('hazard_report', 'Hazard Report'), ('airspace_infringement', 'Airspace Infringement'), ('bird_strike', 'Bird Strike'), ('technical_defect', 'Technical Defect')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('event_datetime', models.DateTimeField()),
                ('event_location', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('immediate_actions', models.TextField(blank=True, null=True)),
                ('contributing_factors', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('dgca_submitted', models.BooleanField(default=False)),
                ('dgca_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dgca_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='infrastructure.aircraft')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='infrastructure.base')),
            ],
            options={
                'db_table': 'occurrence_reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
