# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructure', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereport',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occurrencereport',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.flight'),
        ),
        migrations.AddField(
            model_name='occurrencereport',
            name='investigating_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigating_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occurrencereport',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazardentry',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='hazardentry',
            name='identified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identified_hazards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazardentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hazards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditparameterscore',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_scores', to='compliance.auditrecord'),
        ),
        migrations.AddField(
            model_name='auditparameterscore',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.auditparameter'),
        ),
        migrations.AddField(
            model_name='auditparameter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='compliance.auditcategory'),
        ),
        migrations.AddIndex(
            model_name='compliancealert',
            index=models.Index(fields=['is_resolved', 'severity'], name='compliance__is_reso_33c95c_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancealert',
            index=models.Index(fields=['category', 'is_resolved'], name='compliance__categor_17218d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditparameterscore',
            unique_together={('audit', 'parameter')},
        ),
    ]
