from django.utils import timezone
from rest_framework import serializers
from .models import TechLog, SnagEntry, SnagCategory
from apps.core.scheduling_engine import SchedulingRuleEngine


class SnagEntrySerializer(serializers.ModelSerializer):
    aircraft_tail_number = serializers.ReadOnlyField(source="aircraft.tail_number")
    aircraft_type_name   = serializers.ReadOnlyField(source="aircraft.aircraft_type_detail.name")
    triggers_aog         = serializers.ReadOnlyField()
    is_deferred          = serializers.ReadOnlyField()
    is_overdue           = serializers.ReadOnlyField()

    class Meta:
        model = SnagEntry
        fields = "__all__"  # Include all fields when sending data TO the frontend

        # Completely ignore these fields when receiving data FROM the frontend
        read_only_fields = [
            # Auto-generated by Django
            "id",
            "reported_at",
            "created_at",
            "updated_at",

            # Manually injected by our views.py during closeout
            "tech_log",
            "aircraft",
            "reported_by",

            # Maintenance fields (Pilots shouldn't write to these during closeout)
            "maintenance_record",
            "resolved_at",
            "resolved_by",
            "resolution_notes",

            # CAMO-only fields — only writable via SnagEntryViewSet.set_timeline (H2 Fix)
            "camo_notes",
            "resolution_due_date",
            "camo_approved_by",
        ]


class TechLogSerializer(serializers.ModelSerializer):
    snags = SnagEntrySerializer(many=True, read_only=True)

    class Meta:
        model = TechLog
        fields = "__all__"
        read_only_fields = ["id", "created_at", "updated_at", "flight_duration_minutes"]

    def to_representation(self, instance):
        # 1. Get the standard serialized data
        data = super().to_representation(instance)
        flight = instance.flight

        # 2. Run the single source of truth (Scheduling Rule Engine)
        engine = SchedulingRuleEngine()

        # Note: If your flight model stores flight_type as a string, check if it's solo
        is_solo = flight.flight_type in ['solo', 'cross_country_solo', 'night_solo', 'proficiency_check']

        # Use actual duration for closed tech logs; fall back to scheduled estimate while open
        is_closed = instance.status == 'closed' or (instance.flight_duration_minutes and instance.flight_duration_minutes > 0)
        duration_for_check = instance.flight_duration_minutes if is_closed else flight.duration_minutes

        # We pass None for weather here unless you have a weather service hooked up to the flight
        result = engine.check(
            student=flight.student,
            instructor=flight.instructor,
            aircraft=flight.aircraft,
            duration_minutes=duration_for_check,
            is_solo=is_solo,
            weather=None,
            route=getattr(flight, 'cross_country_route', None),
        )

        # 3. Convert the list of RuleResult objects into a simple dictionary: {'rule_name': True/False}
        checks_dict = {check.name: check.passed for check in result.checks}

        # 4. Map the engine's exact results to the React UI flags
        data['student_medical_valid'] = checks_dict.get('student_medical_valid', True)
        data['student_spl_valid']     = checks_dict.get('student_spl_valid', True)

        # FDTL is OK only if daily, weekly, and monthly all passed
        data['instructor_fdtl_ok'] = (
            checks_dict.get('instructor_fdtl_daily', True) and
            checks_dict.get('instructor_fdtl_weekly', True) and
            checks_dict.get('instructor_fdtl_monthly', True)
        )

        # Aircraft is OK if it passed 50hr, 100hr, and annual checks
        data['aircraft_hours_ok'] = (
            checks_dict.get('aircraft_50hr_ferry_buffer', True) and
            checks_dict.get('aircraft_100hr_ferry_buffer', True) and
            checks_dict.get('aircraft_annual_due', True)
        )

        # Ferry buffer is handled intrinsically by your aircraft hour checks in the engine
        data['ferry_buffer_ok'] = checks_dict.get('aircraft_50hr_ferry_buffer', True)

        # Crosswind check (will default to True if weather wasn't passed)
        data['crosswind_ok'] = checks_dict.get('crosswind_within_student_limit', True)

        return data

    def validate(self, data):
        # Enforce hobbs_in >= hobbs_out
        hobbs_in  = data.get("hobbs_in",  getattr(self.instance, "hobbs_in",  None))
        hobbs_out = data.get("hobbs_out", getattr(self.instance, "hobbs_out", None))
        if hobbs_in is not None and hobbs_out is not None and hobbs_in < hobbs_out:
            raise serializers.ValidationError("hobbs_in must be >= hobbs_out.")
        return data


class OffBlockSerializer(serializers.Serializer):
    """POST /tech-logs/{id}/off-block/"""
    off_block_time = serializers.DateTimeField()


class InstrumentTimeEntryInputSerializer(serializers.Serializer):
    """Inline input for per-seat instrument time at closeout."""
    person_id = serializers.UUIDField()
    seat      = serializers.ChoiceField(choices=['p1', 'p2'])
    time_kind = serializers.ChoiceField(choices=['simulated', 'actual'])
    minutes   = serializers.IntegerField(min_value=1)


class CloseoutSerializer(serializers.Serializer):
    """POST /tech-logs/{id}/closeout/ — post-flight data entry."""
    hobbs_in      = serializers.DecimalField(max_digits=8, decimal_places=1)
    tacho_in      = serializers.DecimalField(max_digits=8, decimal_places=1)
    on_block_time = serializers.DateTimeField()
    crew_pin      = serializers.CharField(max_length=10, write_only=True)
    nil_defects   = serializers.BooleanField()
    snags         = SnagEntrySerializer(many=True, required=False)
    p1_us_passed  = serializers.BooleanField(required=False, allow_null=True)
    # Instrument time entries — one row per (person, time_kind).
    # UI: hidden behind "IF Time" toggle; mandatory if flight was flagged for instrument.
    instrument_entries = InstrumentTimeEntryInputSerializer(many=True, required=False)
    # Cross-country early termination
    cc_terminated_early   = serializers.BooleanField(required=False, default=False)
    cc_termination_reason = serializers.ChoiceField(
        choices=[("weather", "Weather"), ("mechanical", "Mechanical/Snag"), ("other", "Other")],
        required=False, allow_blank=True, allow_null=True
    )
    cc_termination_notes  = serializers.CharField(required=False, allow_blank=True, allow_null=True)

    def validate(self, data):
        return data
