import json
from django.core.management.base import BaseCommand
from django.db import transaction
from apps.syllabus.models import SyllabusStage, SyllabusLesson, SyllabusExercise

RAW_JSON = """[
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D1",
        "title": "Air Fam",
        "flight_type": "dual",
        "seq_order": 1,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D2",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 2,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D3",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 3,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D4",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 4,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D5",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 5,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D6",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 6,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "K1",
        "title": "K1",
        "flight_type": "knowledge_test",
        "seq_order": 7,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D7",
        "title": "PC",
        "flight_type": "progress_check",
        "seq_order": 8,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D8",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 9,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D9",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 10,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D10",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 11,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D11",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 12,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D12",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 13,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "K2",
        "title": "K2",
        "flight_type": "knowledge_test",
        "seq_order": 14,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D13",
        "title": "PC",
        "flight_type": "progress_check",
        "seq_order": 15,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D14",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 16,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D15",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 17,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D16",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 18,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D17",
        "title": "CL",
        "flight_type": "dual",
        "seq_order": 19,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D18",
        "title": "CL Div",
        "flight_type": "cross_country_dual",
        "seq_order": 20,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.75,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "K3",
        "title": "K3",
        "flight_type": "knowledge_test",
        "seq_order": 21,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D19",
        "title": "1st Solo",
        "flight_type": "dual",
        "seq_order": 22,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P1",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 23,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.25,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D20",
        "title": "2nd Solo",
        "flight_type": "dual",
        "seq_order": 24,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P2",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 25,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D21",
        "title": "3rd Solo",
        "flight_type": "dual",
        "seq_order": 26,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P3",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 27,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "K4",
        "title": "K4",
        "flight_type": "knowledge_test",
        "seq_order": 28,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D22",
        "title": "4th Solo",
        "flight_type": "dual",
        "seq_order": 29,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P4",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 30,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P5",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 31,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P6",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 32,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P7",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 33,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P8",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 34,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D23",
        "title": "PC",
        "flight_type": "progress_check",
        "seq_order": 35,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P9",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 36,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P10",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 37,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P11",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 38,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P12",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 39,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P13",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 40,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "D24",
        "title": "PC",
        "flight_type": "progress_check",
        "seq_order": 41,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P14",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 42,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P15",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 43,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P16",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 44,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P17",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 45,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 2,
        "stage_title": "Phase II - Pre-Solo Phase",
        "stage_desc": "General Flying, Circuits & Landings leading to 1st Solo",
        "code": "P18",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 46,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "S1",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 1,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "S2",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 2,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "S3",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 3,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "S4",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 4,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "S5",
        "title": "PC IF",
        "flight_type": "fstd_progress_check",
        "seq_order": 5,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "K5",
        "title": "K5",
        "flight_type": "knowledge_test",
        "seq_order": 6,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D25",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 7,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D26",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 8,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D27",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 9,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D28",
        "title": "GF",
        "flight_type": "dual",
        "seq_order": 10,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D29",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 11,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D30",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 12,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D31",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 13,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D32",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 14,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "K6",
        "title": "K6",
        "flight_type": "knowledge_test",
        "seq_order": 15,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D33",
        "title": "PC",
        "flight_type": "progress_check",
        "seq_order": 16,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P19",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 17,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P20",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 18,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P21",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 19,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P22",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 20,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P23",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 21,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D34",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 22,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D35",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 23,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P24",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 24,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P25",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 25,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P26",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 26,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P27",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 27,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P28",
        "title": "GF",
        "flight_type": "solo",
        "seq_order": 28,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D36",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 29,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 0.75
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "D37",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 30,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 0.75
    },
    {
        "stage_number": 3,
        "stage_title": "Phase III - Instrument & General Flying Phase",
        "stage_desc": "FSTD Simulator IF & Advanced General Flying",
        "code": "P29",
        "title": "CL",
        "flight_type": "solo",
        "seq_order": 31,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "S6",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 1,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "S7",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 2,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "S8",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 3,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "S9",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 4,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "S10",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 5,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 2.5,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "S11",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 6,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 2.5,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "S12",
        "title": "PC IF",
        "flight_type": "fstd_progress_check",
        "seq_order": 7,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 2.0,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "K7",
        "title": "K7",
        "flight_type": "knowledge_test",
        "seq_order": 8,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D38",
        "title": "Snav",
        "flight_type": "cross_country_dual",
        "seq_order": 9,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D39",
        "title": "SNav",
        "flight_type": "cross_country_dual",
        "seq_order": 10,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D40",
        "title": "LNav",
        "flight_type": "cross_country_dual",
        "seq_order": 11,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D41",
        "title": "LNav",
        "flight_type": "cross_country_dual",
        "seq_order": 12,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D42",
        "title": "Lnav OT",
        "flight_type": "cross_country_dual",
        "seq_order": 13,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D43",
        "title": "Lnav OT",
        "flight_type": "cross_country_dual",
        "seq_order": 14,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "K8",
        "title": "K8",
        "flight_type": "knowledge_test",
        "seq_order": 15,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D44",
        "title": "NC",
        "flight_type": "cross_country_dual",
        "seq_order": 16,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 0.5
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P30",
        "title": "SNav",
        "flight_type": "cross_country_solo",
        "seq_order": 17,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P31",
        "title": "SNav",
        "flight_type": "cross_country_solo",
        "seq_order": 18,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P32",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 19,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D45",
        "title": "IF",
        "flight_type": "cross_country_dual",
        "seq_order": 20,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P33",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 21,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P34",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 22,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P35",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 23,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P36",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 24,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P37",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 25,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D46",
        "title": "IF",
        "flight_type": "cross_country_dual",
        "seq_order": 26,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P38",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 27,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P39",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 28,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P40",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 29,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P41",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 30,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D47",
        "title": "IF",
        "flight_type": "cross_country_dual",
        "seq_order": 31,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P42",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 32,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P43",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 33,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P44",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 34,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P45",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 35,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D48",
        "title": "IF",
        "flight_type": "cross_country_dual",
        "seq_order": 36,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D49",
        "title": "IF3001",
        "flight_type": "cross_country_dual",
        "seq_order": 37,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D50",
        "title": "IF3002",
        "flight_type": "cross_country_dual",
        "seq_order": 38,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.75,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P46",
        "title": "LN300",
        "flight_type": "cross_country_solo",
        "seq_order": 39,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 4.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P47",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 40,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P48",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 41,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D51",
        "title": "IF",
        "flight_type": "cross_country_dual",
        "seq_order": 42,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P49",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 43,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P50",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 44,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P51",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 45,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P52",
        "title": "LNav",
        "flight_type": "cross_country_solo",
        "seq_order": 46,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D52",
        "title": "IF",
        "flight_type": "cross_country_dual",
        "seq_order": 47,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P53",
        "title": "Lnav-Buffer",
        "flight_type": "cross_country_solo",
        "seq_order": 48,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P54",
        "title": "Lnav-Buffer",
        "flight_type": "cross_country_solo",
        "seq_order": 49,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P55",
        "title": "Lnav-Buffer",
        "flight_type": "cross_country_solo",
        "seq_order": 50,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 2.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "P56",
        "title": "Snav-Buffer",
        "flight_type": "cross_country_solo",
        "seq_order": 51,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 4,
        "stage_title": "Phase IV - Instrument & Navigation Phase",
        "stage_desc": "Dual and Solo Cross-Country Navigation & Advanced Instrument Flying",
        "code": "D53",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 52,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.0
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "K9",
        "title": "K9",
        "flight_type": "knowledge_test",
        "seq_order": 1,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D54",
        "title": "Night",
        "flight_type": "dual_night",
        "seq_order": 2,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D55",
        "title": "1st SC",
        "flight_type": "dual_night",
        "seq_order": 3,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 0.75,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "P57",
        "title": "1st Solo",
        "flight_type": "solo",
        "seq_order": 4,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.25,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D56",
        "title": "2nd SC",
        "flight_type": "dual_night",
        "seq_order": 5,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 0.75,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "P58",
        "title": "2nd Solo",
        "flight_type": "solo",
        "seq_order": 6,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D57",
        "title": "3rd SC",
        "flight_type": "dual_night",
        "seq_order": 7,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 0.75,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "P59",
        "title": "3rd Solo",
        "flight_type": "solo",
        "seq_order": 8,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "P60",
        "title": "NF CL",
        "flight_type": "night_solo",
        "seq_order": 9,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 0.75,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "P61",
        "title": "NF CL",
        "flight_type": "night_solo",
        "seq_order": 10,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "P62",
        "title": "NF CL",
        "flight_type": "night_solo",
        "seq_order": 11,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "P63",
        "title": "NF CL",
        "flight_type": "night_solo",
        "seq_order": 12,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "K10",
        "title": "K10",
        "flight_type": "knowledge_test",
        "seq_order": 13,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D58",
        "title": "NC-120",
        "flight_type": "dgca_flight_test",
        "seq_order": 14,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": true,
        "dual_hours": null,
        "solo_hours": 1.5,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D59",
        "title": "Nav IF",
        "flight_type": "cross_country_dual",
        "seq_order": 15,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.25,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 2.0
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "K11",
        "title": "K11",
        "flight_type": "knowledge_test",
        "seq_order": 16,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D60",
        "title": "NC-250",
        "flight_type": "dgca_flight_test",
        "seq_order": 17,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": true,
        "dual_hours": null,
        "solo_hours": 3.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D61",
        "title": "Buffer",
        "flight_type": "dual",
        "seq_order": 18,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D62",
        "title": "Buffer",
        "flight_type": "dual",
        "seq_order": 19,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D63",
        "title": "Buffer",
        "flight_type": "dual",
        "seq_order": 20,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D64",
        "title": "Buffer",
        "flight_type": "dual",
        "seq_order": 21,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D65",
        "title": "Buffer",
        "flight_type": "dual",
        "seq_order": 22,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D66",
        "title": "Buffer",
        "flight_type": "dual",
        "seq_order": 23,
        "is_buffer": true,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D67",
        "title": "DTP",
        "flight_type": "dual",
        "seq_order": 24,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D68",
        "title": "GFT(D)",
        "flight_type": "dgca_flight_test",
        "seq_order": 25,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": true,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D69",
        "title": "NTP",
        "flight_type": "dual_night",
        "seq_order": 26,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 5,
        "stage_title": "Phase V - End of Course Phase (Single Engine)",
        "stage_desc": "Night Flying, Solo Cross-Country & DGCA Single-Engine Flight Tests",
        "code": "D70",
        "title": "GFT(N)",
        "flight_type": "dgca_flight_test",
        "seq_order": 27,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": true,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "S13",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 1,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.5,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "S14",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 2,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.5,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "S15",
        "title": "IF",
        "flight_type": "fstd_instrument",
        "seq_order": 3,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": 1.0,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "K12",
        "title": "K12",
        "flight_type": "knowledge_test",
        "seq_order": 4,
        "is_buffer": false,
        "is_knowledge_test": true,
        "log_as_p1_us": false,
        "dual_hours": null,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D71",
        "title": "Fam-Day",
        "flight_type": "dual_multi_engine",
        "seq_order": 5,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D72",
        "title": "CL- 6",
        "flight_type": "dual_multi_engine",
        "seq_order": 6,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D73",
        "title": "Asym",
        "flight_type": "dual_multi_engine",
        "seq_order": 7,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D74",
        "title": "Ab Proc & EM",
        "flight_type": "dual_multi_engine",
        "seq_order": 8,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D75",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 9,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 1.25
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D76",
        "title": "Fam-Night",
        "flight_type": "dual_multi_engine",
        "seq_order": 10,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D77",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 11,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 2.5,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 2.25
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D78",
        "title": "GFT(D)",
        "flight_type": "dgca_flight_test",
        "seq_order": 12,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": true,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D79",
        "title": "GFT(N)",
        "flight_type": "dgca_flight_test",
        "seq_order": 13,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": true,
        "dual_hours": null,
        "solo_hours": 1.0,
        "fstd_hours": null,
        "instrument_hours": null
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D80",
        "title": "IRT",
        "flight_type": "dgca_flight_test",
        "seq_order": 14,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": true,
        "dual_hours": null,
        "solo_hours": 1.5,
        "fstd_hours": null,
        "instrument_hours": 1.25
    },
    {
        "stage_number": 6,
        "stage_title": "Phase VI - Multi Engine Phase",
        "stage_desc": "Multi-Engine Ground, Simulator & DGCA Multi-Engine Rating Flight Tests",
        "code": "D81",
        "title": "IF",
        "flight_type": "dual_instrument",
        "seq_order": 15,
        "is_buffer": false,
        "is_knowledge_test": false,
        "log_as_p1_us": false,
        "dual_hours": 1.0,
        "solo_hours": null,
        "fstd_hours": null,
        "instrument_hours": 0.25
    }
]"""
CPL_EXERCISES_DATA = json.loads(RAW_JSON)

class Command(BaseCommand):
    help = 'Seeds complete CPL Flying Training Syllabus (171 exercises across 6 phases) from embedded FTS data'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Seeding CPL Syllabus data...'))
        
        stages = {}
        lessons = {}
        total_created = 0

        with transaction.atomic():
            for item in CPL_EXERCISES_DATA:
                stg_num = item['stage_number']
                if stg_num not in stages:
                    stage, _ = SyllabusStage.objects.update_or_create(
                        licence_type=SyllabusStage.LicenceType.CPL,
                        stage_number=stg_num,
                        defaults={
                            'title': item['stage_title'],
                            'description': item['stage_desc'],
                            'sequence_order': stg_num,
                        }
                    )
                    stages[stg_num] = stage

                    lesson, _ = SyllabusLesson.objects.update_or_create(
                        stage=stage,
                        lesson_number=1,
                        defaults={
                            'title': f"{stage.title} Core Exercises",
                            'sequence_order': 1,
                        }
                    )
                    lessons[stg_num] = lesson

                lesson = lessons[stg_num]

                exercise, _ = SyllabusExercise.objects.update_or_create(
                    lesson=lesson,
                    exercise_code=item['code'],
                    defaults={
                        'title': item['title'],
                        'description': f"{item['code']} - {item['title']} ({item['stage_title']})",
                        'flight_type_required': item['flight_type'],
                        'pass_grade': 3,
                        'sequence_order': item['seq_order'],
                        'is_buffer': item['is_buffer'],
                        'is_knowledge_test': item['is_knowledge_test'],
                        'log_as_p1_us': item['log_as_p1_us'],
                        'dual_hours': item['dual_hours'],
                        'solo_hours': item['solo_hours'],
                        'fstd_hours': item['fstd_hours'],
                        'instrument_hours': item['instrument_hours'],
                    }
                )
                total_created += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {total_created} CPL Syllabus Exercises across 6 Stages!'))
