# Generated by Django 4.2.14 on 2026-07-01 06:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('billing_type', models.CharField(choices=[('course_fee', 'Course Fee'), ('block_hours', 'Block Hour Package'), ('exam_fee', 'Exam Fee'), ('misc', 'Miscellaneous')], max_length=30)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('hsn_sac_code', models.CharField(default='999293', max_length=10)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_path', models.TextField(blank=True, help_text='MinIO object key for PDF invoice', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'billing_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmiInstalment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instalment_number', models.SmallIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'emi_instalments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='EmiPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_instalments', models.SmallIntegerField()),
                ('amount_per_instalment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emi_plans', to='finance.billingrecord')),
            ],
            options={
                'db_table': 'emi_plans',
            },
        ),
    ]
