# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emiplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emi_plans', to='users.student'),
        ),
        migrations.AddField(
            model_name='emiinstalment',
            name='emi_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='finance.emiplan'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_records', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='emiinstalment',
            unique_together={('emi_plan', 'instalment_number')},
        ),
    ]
