# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestedRoster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion', models.JSONField(help_text='Structured roster returned by Claude')),
                ('prompt_used', models.TextField(help_text='Full prompt sent to Claude (for audit)')),
                ('model_used', models.CharField(default='claude-sonnet-4-6', max_length=50)),
                ('confirmed', models.BooleanField(default=False, help_text='True once scheduling officer confirmed and flights were created')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_suggested_rosters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlanRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_date', models.DateField(db_index=True)),
                ('deadline', models.DateTimeField(help_text='Instructors must submit by this time')),
                ('status', models.CharField(choices=[('open', 'Open (awaiting submissions)'), ('closed', 'Closed (deadline passed)'), ('rostered', 'Roster generated')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Instructions or context for instructors', null=True)),
            ],
            options={
                'db_table': 'daily_plan_requests',
                'ordering': ['-plan_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorDailyPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability_start', models.TimeField(help_text='Earliest the instructor can fly')),
                ('availability_end', models.TimeField(help_text='Latest the instructor can finish')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved by CFI')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor_daily_plans',
            },
        ),
        migrations.CreateModel(
            name='InstructorDailyPlanEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_start', models.TimeField(blank=True, null=True)),
                ('estimated_duration_min', models.IntegerField(default=60)),
                ('prereq_met', models.BooleanField(default=True, help_text='False when previous exercise not yet passed')),
                ('cfi_override_requested', models.BooleanField(default=False)),
                ('cfi_override_approved', models.BooleanField(default=False)),
                ('cfi_override_reason', models.TextField(blank=True, null=True)),
                ('sequence_order', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'instructor_daily_plan_entries',
                'ordering': ['sequence_order', 'preferred_start'],
            },
        ),
        migrations.CreateModel(
            name='InstructorStudentAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor_student_assignments',
                'ordering': ['instructor', 'student'],
            },
        ),
    ]
