# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0001_initial'),
        ('users', '0001_initial'),
        ('rostering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorstudentassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorstudentassignment',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='instructorstudentassignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='instructorstudentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='users.student'),
        ),
        migrations.AddField(
            model_name='instructordailyplanentry',
            name='cfi_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructordailyplanentry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syllabus.syllabusexercise'),
        ),
        migrations.AddField(
            model_name='instructordailyplanentry',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rostering.instructordailyplan'),
        ),
        migrations.AddField(
            model_name='instructordailyplanentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='instructordailyplan',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_plans', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='instructordailyplan',
            name='plan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_plans', to='rostering.dailyplanrequest'),
        ),
        migrations.AddField(
            model_name='dailyplanrequest',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_requests', to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='dailyplanrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisuggestedroster',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisuggestedroster',
            name='plan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='rostering.dailyplanrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorstudentassignment',
            unique_together={('instructor', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='instructordailyplan',
            unique_together={('plan_request', 'instructor')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyplanrequest',
            unique_together={('plan_date', 'base')},
        ),
    ]
