# Generated by Django 4.2.14 on 2026-07-05 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rostering', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplanrequest',
            name='cfi_comments',
            field=models.TextField(blank=True, help_text='Reason for rejection or changes required', null=True),
        ),
        migrations.AddField(
            model_name='dailyplanrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyplanrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rosters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyplanrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open (awaiting submissions)'), ('closed', 'Closed (Drafting In progress)'), ('pending_cfi_approval', 'Pending CFI Approval'), ('rejected_by_cfi', 'Rejected by CFI (Needs correction)'), ('rostered', 'Roster generated')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructordailyplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('leave', 'On Leave'), ('approved', 'Approved by CFI')], default='pending', max_length=20),
        ),
    ]
