# Generated by Django 4.2.14 on 2026-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0003_dailyplanrequest_cfi_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisuggestedroster',
            name='model_used',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='aisuggestedroster',
            name='prompt_used',
            field=models.TextField(help_text='Full prompt sent to Gemini (for audit)'),
        ),
        migrations.AlterField(
            model_name='aisuggestedroster',
            name='suggestion',
            field=models.JSONField(help_text='Structured roster returned by Gemini'),
        ),
    ]
