# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_type', models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo'), ('cross_country_dual', 'Cross-Country Dual'), ('cross_country_solo', 'Cross-Country Solo'), ('night_dual', 'Night Dual'), ('night_solo', 'Night Solo'), ('instrument', 'Instrument'), ('ferry', 'Ferry'), ('proficiency_check', 'Proficiency Check')], max_length=30)),
                ('is_ferry', models.BooleanField(default=False)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('airborne', 'Airborne'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('aborted', 'Aborted')], db_index=True, default='scheduled', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flights',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='FlightExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_order', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'flight_exercises',
            },
        ),
        migrations.CreateModel(
            name='InstructorDutyLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duty_start', models.DateTimeField()),
                ('duty_end', models.DateTimeField(blank=True, null=True)),
                ('flight_minutes', models.IntegerField(default=0)),
                ('total_duty_minutes', models.IntegerField(blank=True, null=True)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.base')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.flight')),
            ],
            options={
                'db_table': 'instructor_duty_logs',
            },
        ),
    ]
