# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('infrastructure', '0001_initial'),
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructordutylog',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='flightexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syllabus.syllabusexercise'),
        ),
        migrations.AddField(
            model_name='flightexercise',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='scheduling.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='infrastructure.aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='flight',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='flight',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='users.student'),
        ),
        migrations.AddField(
            model_name='flight',
            name='weather_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weathercache'),
        ),
        migrations.AddIndex(
            model_name='instructordutylog',
            index=models.Index(fields=['instructor', 'duty_start'], name='instructor__instruc_116c76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightexercise',
            unique_together={('flight', 'exercise')},
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['base', 'scheduled_start'], name='flights_base_id_156ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['aircraft', 'scheduled_start'], name='flights_aircraf_a03e69_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['instructor', 'scheduled_start'], name='flights_instruc_690fa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='chk_flight_window'),
        ),
    ]
