# Generated by Django 4.2.14 on 2026-07-05 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0003_alter_flight_flight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='ba_test_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='dispatcher_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='dispatcher_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='preflight_briefing_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Pending CFI Approval)'), ('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('airborne', 'Airborne'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('aborted', 'Aborted'), ('suspended', 'Suspended (Conflict Resolution)')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
