# Generated by Django 4.2.14 on 2026-07-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dispatch_pin'),
        ('scheduling', '0004_flight_aircraft_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='override_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='secondary_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_flights', to='users.instructor'),
        ),
    ]
