# Generated by Django 4.2.14 on 2026-07-09 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dispatch_pin'),
        ('scheduling', '0005_flight_override_reason_flight_override_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='users.instructor'),
        ),
    ]
