# Generated by Django 4.2.14 on 2026-07-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0006_alter_flight_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorFlightLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_date', models.DateField(db_index=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('aircraft_regn', models.CharField(blank=True, max_length=30, null=True)),
                ('pic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('co_pilot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_from', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_to', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=10, null=True)),
                ('dual_minutes', models.IntegerField(default=0)),
                ('pic_minutes', models.IntegerField(default=0)),
                ('copilot_minutes', models.IntegerField(default=0)),
                ('instrument_minutes', models.IntegerField(default=0)),
                ('instructional_minutes', models.IntegerField(default=0)),
                ('exercises', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(default='Approved', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_flight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prior_flight_logs',
                'ordering': ['-flight_date'],
                'indexes': [models.Index(fields=['user', 'flight_date'], name='prior_fligh_user_id_3a2085_idx')],
            },
        ),
    ]
