# Generated by Django 4.2.14 on 2026-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_flight_flight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorflightlog',
            name='is_multi_engine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='priorflightlog',
            name='me_day_p1_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priorflightlog',
            name='me_day_p2_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priorflightlog',
            name='me_day_ut_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priorflightlog',
            name='me_night_p1_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priorflightlog',
            name='me_night_p2_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priorflightlog',
            name='me_night_ut_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
