# Generated by Django 4.2.14 on 2026-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_priorflightlog_is_multi_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo'), ('cross_country_dual', 'Cross-Country Dual'), ('cross_country_solo', 'Cross-Country Solo'), ('night_dual', 'Night Dual'), ('night_solo', 'Night Solo'), ('instrument', 'Instrument'), ('dual_instrument', 'Dual Instrument'), ('dual_multi_engine', 'Dual Multi-Engine'), ('instructor_dual', 'Instructor Dual'), ('ferry', 'Ferry'), ('proficiency_check', 'Proficiency Check'), ('progress_check', 'Progress Check'), ('knowledge_test', 'Ground Knowledge Test'), ('ground_training', 'Ground Training'), ('licensing_process', 'Licensing Process'), ('fstd_instrument', 'FSTD Simulator Instrument'), ('fstd_progress_check', 'FSTD Simulator Progress Check'), ('dgca_flight_test', 'DGCA Flight Test (P1 U/S Logged)'), ('buffer', 'Buffer')], max_length=30),
        ),
    ]
