# Generated by Django 4.2.14 on 2026-08-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fstd', '0001_initial'),
        ('scheduling', '0010_alter_flight_flight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='day_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flight',
            name='external_p1_name',
            field=models.CharField(blank=True, help_text='Name and designation of external DGCA Examiner', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='fstd_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fstd.fstddevice'),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_cross_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_external_p1',
            field=models.BooleanField(default=False, help_text='True if P1 is an external DGCA Examiner without a system account'),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_instructional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_instrument_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_instrument_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_simulator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_skill_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flight',
            name='passenger_name',
            field=models.CharField(blank=True, help_text='For joyrides/intro flights', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('dual', 'Dual'), ('solo', 'Solo')], max_length=30),
        ),
    ]
