# Generated by Django 4.2.14 on 2026-08-06 14:31

from django.db import migrations


def populate_flags(apps, schema_editor):
    Flight = apps.get_model('scheduling', 'Flight')
    for flight in Flight.objects.all():
        old_type = getattr(flight, 'flight_type', '')
        
        # Determine DUAL vs SOLO
        if 'solo' in old_type or old_type in ['proficiency_check']:
            flight.flight_type = 'solo'
        else:
            flight.flight_type = 'dual'
            
        # Determine Characteristic Flags
        if 'cross_country' in old_type:
            flight.is_cross_country = True
        if 'night' in old_type:
            flight.is_night = True
        if 'instrument' in old_type:
            flight.is_instrument_actual = True  # Assuming actual for existing logs
        if old_type in ['proficiency_check']:
            flight.is_skill_test = True
        if old_type == 'ferry':
            flight.is_ferry = True
            
        if flight.instructor_id:
            flight.is_instructional = True
            
        flight.save(update_fields=['flight_type', 'is_cross_country', 'is_night', 
                                   'is_instrument_actual', 'is_skill_test', 'is_ferry', 'is_instructional'])

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_flight_day_hours_flight_external_p1_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_flags, reverse_populate),
    ]
