# Generated by Django 4.2.14 on 2026-08-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_populate_flight_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='p1_us_credited',
            field=models.BooleanField(default=False),
        ),
    ]
