# Generated by Django 4.2.14 on 2026-08-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
        ('scheduling', '0013_flight_p1_us_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='cross_country_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='navigation.crosscountryroute'),
        ),
    ]
