# Generated by Django 4.2.14 on 2026-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_flight_cross_country_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorflightlog',
            name='instructional_night_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
