# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('cfi', 'Chief Flight Instructor'), ('instructor', 'Instructor / FI'), ('dispatcher', 'Dispatcher / Operations'), ('student', 'Student Pilot'), ('camo', 'CAMO Manager'), ('safety_officer', 'Safety & Compliance Officer'), ('finance', 'Finance Manager')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('token_version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('home_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.base')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cfi_licence_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cfi_expiry', models.DateField(blank=True, null=True)),
                ('fdtl_daily_remaining_min', models.IntegerField(default=480, help_text='8 hrs = 480 min')),
                ('fdtl_weekly_remaining_min', models.IntegerField(default=1800, help_text='30 hrs = 1800 min')),
                ('fdtl_monthly_remaining_min', models.IntegerField(default=6000, help_text='100 hrs = 6000 min')),
                ('fdtl_last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('instrument_rating', models.BooleanField(default=False)),
                ('multi_engine_rating', models.BooleanField(default=False)),
                ('type_rating_ids', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spl_number', models.CharField(blank=True, max_length=50, null=True)),
                ('spl_issue_date', models.DateField(blank=True, null=True)),
                ('spl_expiry', models.DateField(blank=True, null=True)),
                ('medical_class', models.SmallIntegerField(blank=True, choices=[(1, 'Class 1'), (2, 'Class 2')], null=True)),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('frtol_number', models.CharField(blank=True, max_length=50, null=True)),
                ('frtol_expiry', models.DateField(blank=True, null=True)),
                ('hours_total', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('hours_pic', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('hours_dual', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('hours_solo', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('hours_cross_country', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('hours_night', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('hours_instrument', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('solo_approved', models.BooleanField(default=False)),
                ('solo_approved_at', models.DateTimeField(blank=True, null=True)),
                ('solo_max_crosswind_kt', models.DecimalField(decimal_places=1, default=7.0, max_digits=4)),
                ('batch_number', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('target_licence', models.CharField(choices=[('PPL', 'Private Pilot Licence'), ('CPL', 'Commercial Pilot Licence')], default='CPL', max_length=10)),
                ('solo_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('spl', 'Student Pilot Licence'), ('medical_class1', 'Medical Certificate Class 1'), ('medical_class2', 'Medical Certificate Class 2'), ('frtol', 'Radio Telephony Operator Licence'), ('atpl_theory', 'ATPL Theory Credits'), ('cpl', 'Commercial Pilot Licence')], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring_soon', 'Expiring Soon (< 60 days)'), ('expired', 'Expired'), ('pending_renewal', 'Pending Renewal')], default='valid', max_length=20)),
                ('file_path', models.TextField(blank=True, help_text='MinIO object key', null=True)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256', max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_superseded', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.student')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
