# Generated by Django 4.2.14 on 2026-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispatch_pin',
            field=models.CharField(blank=True, help_text='Hashed PIN for dispatch/acceptance signatures.', max_length=128, null=True),
        ),
    ]
