# Generated by Django 4.2.14 on 2026-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dispatch_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_instructional',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_instrument',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_pic',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_total',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_cross_country',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_dual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_instrument',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_night',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_pic',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_solo',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_total',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
    ]
