# Generated by Django 4.2.14 on 2026-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructor_previous_hours_instructional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hours_p1_us',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Hours logged as PIC Under Supervision (GFT, IRT, NC-120, NC-250)', max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_p1_us',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
    ]
