# Generated by Django 4.2.14 on 2026-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_hours_p1_us_student_previous_hours_p1_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='hours_multi_engine',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_multi_engine',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_multi_engine',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_multi_engine',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
    ]
