# Generated by Django 4.2.14 on 2026-07-25 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_instructor_hours_multi_engine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='cfi_expiry',
            new_name='frtol_expiry',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='cfi_licence_number',
        ),
        migrations.AddField(
            model_name='instructor',
            name='cpl_atpl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='cpl_atpl_number',
            field=models.CharField(blank=True, help_text='CPL / ATPL Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fir_expiry',
            field=models.DateField(blank=True, help_text='AFIR / FIR Expiry Date', null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fir_licence_number',
            field=models.CharField(blank=True, help_text='AFIR / FIR Licence Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fir_rating_type',
            field=models.CharField(choices=[('AFIR', 'Assistant Flight Instructor Rating'), ('FIR', 'Flight Instructor Rating')], default='AFIR', max_length=10),
        ),
        migrations.AddField(
            model_name='instructor',
            name='frtol_number',
            field=models.CharField(blank=True, help_text='FRTOL Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='ir_expiry',
            field=models.DateField(blank=True, help_text='Instrument Rating Expiry', null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='medical_class1_expiry',
            field=models.DateField(blank=True, help_text='Class 1 Medical Expiry', null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique Employee / Registration ID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('spl', 'Student Pilot Licence'), ('cpl', 'Commercial Pilot Licence'), ('atpl', 'Airline Transport Pilot Licence'), ('fir_afir', 'Flight Instructor Rating (AFIR / FIR)'), ('medical_class1', 'Medical Certificate Class 1'), ('medical_class2', 'Medical Certificate Class 2'), ('frtol', 'Radio Telephony Operator Licence'), ('ir_certificate', 'Instrument Rating Certificate'), ('other', 'Other Licence / Credential')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file_path',
            field=models.FileField(blank=True, help_text='Scanned Licence or Medical document', null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.student'),
        ),
    ]
