# Generated by Django 4.2.14 on 2026-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_dgca_licences_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('cfi', 'Chief Flight Instructor'), ('instructor', 'Instructor / FI'), ('dispatcher', 'Dispatcher / Operations'), ('student', 'Student Pilot'), ('camo', 'CAMO Manager'), ('safety_officer', 'Safety & Compliance Officer'), ('finance', 'Finance Manager'), ('doctor', 'Doctor / Medical Officer')], db_index=True, max_length=30),
        ),
    ]
