# Generated by Django 4.2.14 on 2026-08-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_licencetype_alter_syllabusstage_licence_type'),
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='target_licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='syllabus.licencetype'),
        ),
    ]
