# Generated by Django 4.2.14 on 2026-08-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_target_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='previous_hours_instrument',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hours_cross_country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hours_instrument',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_hours_cross_country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_hours_instrument',
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_cross_country_dual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_cross_country_pic',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_day',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_fstd',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_instructional',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_instrument_actual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_instrument_simulated',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_night',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_pic',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hours_total',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_cross_country_dual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_cross_country_pic',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_fstd',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_instrument_actual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_instrument_simulated',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='instructor',
            name='previous_hours_night',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_cross_country_dual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_cross_country_pic',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_day',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_fstd',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_instrument_actual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_instrument_simulated',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_cross_country_dual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_cross_country_pic',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_fstd',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_instrument_actual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_hours_instrument_simulated',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
    ]
