# Generated by Django 4.2.14 on 2026-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_instructor_previous_hours_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('cfi', 'Chief Flight Instructor'), ('instructor', 'Instructor / FI'), ('dispatcher', 'Dispatcher / Operations'), ('student', 'Student Pilot'), ('camo', 'CAMO Manager'), ('safety_officer', 'Safety & Compliance Officer'), ('finance', 'Finance Manager'), ('doctor', 'Doctor / Medical Officer'), ('data_officer', 'Aero Data Officer')], db_index=True, max_length=30),
        ),
    ]
