# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icao_code', models.CharField(db_index=True, max_length=4)),
                ('metar_raw', models.TextField(blank=True, null=True)),
                ('taf_raw', models.TextField(blank=True, null=True)),
                ('wind_direction_deg', models.SmallIntegerField(blank=True, null=True)),
                ('wind_speed_kt', models.SmallIntegerField(blank=True, null=True)),
                ('wind_gust_kt', models.SmallIntegerField(blank=True, null=True)),
                ('visibility_m', models.IntegerField(blank=True, null=True)),
                ('temp_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('dewpoint_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('qnh_hpa', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('cloud_layers', models.JSONField(blank=True, default=list)),
                ('density_altitude_ft', models.IntegerField(blank=True, null=True)),
                ('pressure_alt_ft', models.IntegerField(blank=True, null=True)),
                ('observation_time', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_cache',
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
        migrations.CreateModel(
            name='NotamCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icao_code', models.CharField(db_index=True, max_length=4)),
                ('notam_id', models.CharField(max_length=50)),
                ('series', models.CharField(blank=True, max_length=1, null=True)),
                ('notam_type', models.CharField(blank=True, max_length=10, null=True)),
                ('purpose', models.CharField(blank=True, max_length=10, null=True)),
                ('scope', models.CharField(blank=True, max_length=10, null=True)),
                ('lower_limit', models.CharField(blank=True, max_length=20, null=True)),
                ('upper_limit', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('notam_text', models.TextField()),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notam_cache',
                'ordering': ['-fetched_at'],
                'unique_together': {('icao_code', 'notam_id')},
            },
        ),
    ]
