# Generated by Django 4.2.14 on 2026-08-01 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_runway_base_active_runway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercache',
            name='active_runway',
            field=models.ForeignKey(blank=True, help_text='Active runway at time of observation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.runway'),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='User who manually entered this weather data (null for auto-fetch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='source',
            field=models.CharField(choices=[('auto_fetch', 'Auto Fetch'), ('manual', 'Manual Entry')], default='auto_fetch', help_text='Whether this entry was auto-fetched from API or manually entered', max_length=20),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='source_remarks',
            field=models.TextField(blank=True, help_text="e.g. 'Fetched from AVWX API' or 'Manual entry — API unreachable'", null=True),
        ),
    ]
