# Generated by Django 4.2.14 on 2026-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weathercache_active_runway_weathercache_entered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercache',
            name='sunrise_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='sunset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
