# Generated by Django 4.2.14 on 2026-08-06 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_runway_base_active_runway'),
        ('weather', '0003_weathercache_sunrise_time_weathercache_sunset_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathercache',
            name='sunrise_time',
        ),
        migrations.RemoveField(
            model_name='weathercache',
            name='sunset_time',
        ),
        migrations.CreateModel(
            name='SolarSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('sunrise_time', models.DateTimeField()),
                ('sunset_time', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_schedules', to='infrastructure.base')),
            ],
            options={
                'db_table': 'solar_schedules',
                'unique_together': {('base', 'date')},
            },
        ),
    ]
