# Generated by Django 4.2.14 on 2026-08-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0004_aircrafttype_cruise_speed_knots_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icao_code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation_ft', models.IntegerField(default=0)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('has_fuel', models.BooleanField(default=True)),
                ('has_customs', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True, help_text='False for airports pending CFI review')),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_record', to='infrastructure.base')),
            ],
            options={
                'db_table': 'airports',
                'ordering': ['icao_code'],
            },
        ),
        migrations.CreateModel(
            name='CrossCountryRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. VAOP-VAUD-VAOP Triangular', max_length=150)),
                ('is_triangular', models.BooleanField(default=False, help_text='True if route returns to departure via a turn-point')),
                ('total_distance_nm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_departing', to='navigation.airport')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_arriving', to='navigation.airport')),
            ],
            options={
                'db_table': 'cross_country_routes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteNearbyAirport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='navigation.airport')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_airports', to='navigation.crosscountryroute')),
            ],
            options={
                'db_table': 'route_nearby_airports',
            },
        ),
        migrations.CreateModel(
            name='RouteAlternate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alternate_type', models.CharField(choices=[('takeoff', 'Takeoff Alternate'), ('enroute', 'Enroute Alternate'), ('destination', 'Destination Alternate')], max_length=20)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='navigation.airport')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternates', to='navigation.crosscountryroute')),
            ],
            options={
                'db_table': 'route_alternates',
                'ordering': ['route', 'alternate_type'],
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.SmallIntegerField(help_text='1-based ordering of this leg')),
                ('waypoint_name', models.CharField(blank=True, help_text='Non-airport turn point e.g. VOR, reporting point', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('leg_distance_nm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='navigation.airport')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='navigation.crosscountryroute')),
            ],
            options={
                'db_table': 'route_legs',
                'ordering': ['route', 'sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
    ]
