# Generated by Django 4.2.14 on 2026-08-06 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FSTDDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_code', models.CharField(help_text='e.g. SIM-01', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. Cessna 172 FTD Level 5', max_length=150)),
                ('aircraft_type', models.CharField(blank=True, help_text='e.g. C172', max_length=50)),
                ('qualification_level', models.CharField(blank=True, help_text='e.g. FTD Level 5, FNPT II', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FSTD Device',
                'verbose_name_plural': 'FSTD Devices',
                'ordering': ['device_code'],
            },
        ),
    ]
