# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSbDirective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(help_text='DGCA, FAA, EASA', max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('directive_type', models.CharField(choices=[('AD', 'AD'), ('SB', 'SB'), ('SL', 'SL')], max_length=10)),
                ('compliance_status', models.CharField(choices=[('pending', 'Pending'), ('complied', 'Complied With'), ('not_applicable', 'Not Applicable'), ('recurring', 'Recurring')], default='pending', max_length=20)),
                ('compliance_due_date', models.DateField(blank=True, null=True)),
                ('compliance_due_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('next_recurrence_date', models.DateField(blank=True, null=True)),
                ('next_recurrence_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_sb_directives',
                'ordering': ['compliance_due_date'],
            },
        ),
        migrations.CreateModel(
            name='AmeDutyLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ame_duty_logs',
                'ordering': ['-shift_start'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('line', 'Line Maintenance'), ('50hr', '50-Hour Inspection'), ('100hr', '100-Hour Inspection'), ('200hr', '200-Hour Inspection'), ('600hr', '600-Hour Inspection'), ('annual', 'Annual Inspection'), ('biennial', 'Biennial Inspection'), ('unscheduled', 'Unscheduled / Defect Rectification'), ('ad_compliance', 'AD Compliance'), ('sb_compliance', 'SB Compliance')], db_index=True, max_length=30)),
                ('performed_at_hours', models.DecimalField(decimal_places=1, max_digits=8)),
                ('performed_at_date', models.DateField()),
                ('next_due_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('work_order_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ad_sb_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('parts_replaced', models.JSONField(blank=True, default=list)),
                ('labour_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('total_cost_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ame_licence_number', models.CharField(blank=True, max_length=50, null=True)),
                ('crs_issued', models.BooleanField(default=False)),
                ('crs_issued_at', models.DateTimeField(blank=True, null=True)),
                ('crs_document_path', models.TextField(blank=True, help_text='MinIO object key', null=True)),
            ],
            options={
                'db_table': 'maintenance_records',
                'ordering': ['-performed_at_date'],
            },
        ),
        migrations.CreateModel(
            name='SortieGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.SmallIntegerField(help_text='1 (Unsatisfactory) to 5 (Exceptional)')),
                ('instructor_notes', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Immutable after 7 days', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syllabus.syllabusexercise')),
            ],
            options={
                'db_table': 'sortie_grades',
                'ordering': ['-graded_at'],
            },
        ),
    ]
