# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiegrade',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='scheduling.flight'),
        ),
    ]
