# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructure', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiegrade',
            name='graded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_grades', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='sortiegrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='infrastructure.aircraft'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='crs_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_crs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amedutylog',
            name='ame_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ame_duty_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amedutylog',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ame_duty_logs', to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='amedutylog',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='adsbdirective',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directives', to='infrastructure.aircraft'),
        ),
        migrations.AddField(
            model_name='adsbdirective',
            name='complied_via_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancerecord'),
        ),
        migrations.AlterUniqueTogether(
            name='sortiegrade',
            unique_together={('flight', 'exercise')},
        ),
    ]
