# Generated by Django 4.2.14 on 2026-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='planned', help_text="Work order status — aircraft only grounded when status is 'in_progress'", max_length=20),
        ),
    ]
