# Generated by Django 4.2.14 on 2026-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_at_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_at_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
