# Generated by Django 4.2.14 on 2026-08-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_populate_flight_flags'),
        ('maintenance', '0005_alter_maintenancerecord_performed_at_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiegrade',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='scheduling.flight'),
        ),
    ]
