# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnagEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('go', 'Go (Deferred — safe for next flight)'), ('no_go', 'No-Go (Aircraft unairworthy — AOG)'), ('observation', 'Observation (no airworthiness impact)')], db_index=True, max_length=20)),
                ('ata_chapter', models.CharField(blank=True, max_length=10, null=True)),
                ('deferral_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'snag_entries',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TechLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hobbs_out', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('tacho_out', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('dispatch_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('student_medical_valid', models.BooleanField(blank=True, null=True)),
                ('student_spl_valid', models.BooleanField(blank=True, null=True)),
                ('instructor_fdtl_ok', models.BooleanField(blank=True, null=True)),
                ('aircraft_hours_ok', models.BooleanField(blank=True, null=True)),
                ('ferry_buffer_ok', models.BooleanField(blank=True, null=True)),
                ('crosswind_ok', models.BooleanField(blank=True, null=True)),
                ('live_wind_kt', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('live_crosswind_component_kt', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('density_altitude_ft', models.IntegerField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_biometric_ok', models.BooleanField(default=False)),
                ('briefing_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('hobbs_in', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('tacho_in', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('flight_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('nil_defects', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('aog', 'AOG (No-Go Snag Filed)')], db_index=True, default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tech_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
