# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0002_initial'),
        ('scheduling', '0001_initial'),
        ('infrastructure', '0001_initial'),
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techlog',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tech_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techlog',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_logs', to='infrastructure.aircraft'),
        ),
        migrations.AddField(
            model_name='techlog',
            name='briefing_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefing_acks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techlog',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tech_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techlog',
            name='dispatch_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_cleared_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techlog',
            name='flight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tech_log', to='scheduling.flight'),
        ),
        migrations.AddField(
            model_name='techlog',
            name='weather_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weathercache'),
        ),
        migrations.AddField(
            model_name='snagentry',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snags', to='infrastructure.aircraft'),
        ),
        migrations.AddField(
            model_name='snagentry',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolves_snags', to='maintenance.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='snagentry',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_snags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snagentry',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_snags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snagentry',
            name='tech_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snags', to='dispatch.techlog'),
        ),
    ]
