# Generated by Django 4.2.14 on 2026-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techlog',
            name='off_block_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techlog',
            name='on_block_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
