# Generated by Django 4.2.14 on 2026-07-28 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0003_techlog_off_block_time_techlog_on_block_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='snagentry',
            name='camo_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camo_approved_snags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snagentry',
            name='camo_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snagentry',
            name='resolution_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
