# Generated by Django 4.2.14 on 2026-08-01 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0004_snagentry_camo_approved_by_snagentry_camo_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAEquipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='techlog',
            name='ba_test_details',
            field=models.JSONField(blank=True, help_text='Auto-fetched BA test details for student/instructor', null=True),
        ),
        migrations.AddField(
            model_name='techlog',
            name='ba_test_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BATestEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(max_length=50)),
                ('test_serial_number', models.CharField(db_index=True, max_length=100)),
                ('test_time', models.DateTimeField()),
                ('result', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='PASS', max_length=10)),
                ('alcohol_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_ba_tests', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='dispatch.baequipment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ba_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ba_test_entries',
                'ordering': ['-test_time'],
            },
        ),
    ]
