# Generated by Django 4.2.14 on 2026-08-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_baequipment_techlog_ba_test_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batestentry',
            name='alcohol_level',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
