# Generated by Django 4.2.14 on 2026-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_alter_batestentry_alcohol_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlog',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('aog', 'AOG (No-Go Snag Filed)'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20),
        ),
    ]
