# Generated by Django 4.2.14 on 2026-08-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_flight_cross_country_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0008_ba_result_remove_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentTimeEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat', models.CharField(choices=[('p1', 'P1 / PIC'), ('p2', 'P2 / Student / Second Pilot')], max_length=10)),
                ('time_kind', models.CharField(choices=[('simulated', 'Simulated Instrument'), ('actual', 'Actual Instrument (IMC)')], max_length=10)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_entries', to='scheduling.flight')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_time_entries', to=settings.AUTH_USER_MODEL)),
                ('tech_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_entries', to='dispatch.techlog')),
            ],
            options={
                'db_table': 'instrument_time_entries',
                'ordering': ['seat', 'time_kind'],
                'unique_together': {('tech_log', 'person', 'time_kind')},
            },
        ),
    ]
