# Generated by Django 4.2.14 on 2026-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_instrumenttimeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='techlog',
            name='briefing_packet_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of full cross-country briefing (METAR/TAF/NOTAMs) at time of dispatch', null=True),
        ),
    ]
