# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unit', models.CharField(default='each', max_length=20)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit_cost_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['base', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRequisition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_fulfilled', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_method', models.CharField(blank=True, help_text='ferry_flight | ground_transport | courier', max_length=50, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_requisitions',
                'ordering': ['-requested_at'],
            },
        ),
    ]
