# Generated by Django 4.2.14 on 2026-07-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructure', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='dispatch_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.flight'),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='fulfilling_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_requisitions', to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='requesting_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_requisitions', to='infrastructure.base'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='aircraft_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.aircrafttype'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='infrastructure.base'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('base', 'part_number')},
        ),
    ]
